### ISSUE TITLE
object aspects with no corresponding "pair"

### ISSUE THREAD

**Issue by ladyisidore** [iiyo/toothrot#2]
so, so far it seems objects can only have paired aspects - open/closed, locked/unlocked, etc. is it possible for an object to have an aspect without a counterpart? for example, an "examine" aspect that will lead to a node when clicked but not lead to any kind of change in status?

basically, i want to make prototypes for characters and for objects that can't be manipulated, only examined. and obviously, i want the "examine" link to persist even after the object's been looked at once, since there's no way to "unexamine" something.

**Comment by jsteinbeck** [comment]
Sure, you can do that. In fact, the active aspects on an object shouldn't just magically change, but you have to add or drop them manually. The idea here is that once a player clicks on an object action, they are forwarded to another node -- and the object's status only changes when you do that yourself in the target node. So as long as the target node of your "examine" action doesn't drop the "examine" aspect, it should do what you want.

Also, if you've only just started with your project, please be aware that I'm about to release v2 of the engine, and support for the object system has been dropped in that version. In v2 the nodes also function as the former objects, but there's no longer any aspects or prototypes, and no separate objects.json file either. If you want to try the beta, you can install it with `npm install -g toothrot@beta`.
